import { getRawDb } from ".";

let ready: Promise<unknown> | null = null;

export function ensureSchema() {
  const db = getRawDb();
  if (!ready) {
    const statements = [
      `CREATE TABLE IF NOT EXISTS products (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, name text NOT NULL, category text DEFAULT 'Sem categoria' NOT NULL, description text DEFAULT '' NOT NULL, price real DEFAULT 0 NOT NULL, promotional_price real, minimum_price real DEFAULT 0 NOT NULL, cost real DEFAULT 0 NOT NULL, status text DEFAULT 'Ativo' NOT NULL, delivery_days integer DEFAULT 0 NOT NULL, target_audience text DEFAULT '' NOT NULL, problem_solved text DEFAULT '' NOT NULL, sales_arguments text DEFAULT '' NOT NULL, objections text DEFAULT '' NOT NULL, notes text DEFAULT '' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS leads (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, name text NOT NULL, company text DEFAULT '' NOT NULL, phone text DEFAULT '' NOT NULL, whatsapp text DEFAULT '' NOT NULL, email text DEFAULT '' NOT NULL, instagram text DEFAULT '' NOT NULL, site text DEFAULT '' NOT NULL, city text DEFAULT '' NOT NULL, segment text DEFAULT '' NOT NULL, source text DEFAULT 'Indicação' NOT NULL, product_interest text DEFAULT '' NOT NULL, responsible text DEFAULT '' NOT NULL, status text DEFAULT 'Novo' NOT NULL, potential_value real DEFAULT 0 NOT NULL, first_contact text DEFAULT '' NOT NULL, last_contact text DEFAULT '' NOT NULL, next_followup text DEFAULT '' NOT NULL, notes text DEFAULT '' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS sales (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, client text NOT NULL, product_id integer, product_name text NOT NULL, seller text DEFAULT '' NOT NULL, gross_value real DEFAULT 0 NOT NULL, discount real DEFAULT 0 NOT NULL, final_value real DEFAULT 0 NOT NULL, cost real DEFAULT 0 NOT NULL, payment_method text DEFAULT 'Pix' NOT NULL, date text NOT NULL, status text DEFAULT 'Pendente' NOT NULL, notes text DEFAULT '' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS tasks (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, title text NOT NULL, description text DEFAULT '' NOT NULL, responsible text DEFAULT '' NOT NULL, due_date text DEFAULT '' NOT NULL, start_at text DEFAULT '' NOT NULL, end_at text DEFAULT '' NOT NULL, all_day integer DEFAULT false NOT NULL, calendar_color text DEFAULT '#db8a19' NOT NULL, reminder_minutes integer DEFAULT 15 NOT NULL, priority text DEFAULT 'Média' NOT NULL, status text DEFAULT 'A fazer' NOT NULL, lead_id integer, updated_by text DEFAULT 'Equipe comercial' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS goals (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, name text NOT NULL, scope text DEFAULT 'Empresa' NOT NULL, owner_name text DEFAULT 'Empresa' NOT NULL, period_type text DEFAULT 'Mensal' NOT NULL, revenue_target real DEFAULT 0 NOT NULL, sales_target integer DEFAULT 0 NOT NULL, leads_target integer DEFAULT 0 NOT NULL, meetings_target integer DEFAULT 0 NOT NULL, proposals_target integer DEFAULT 0 NOT NULL, start_date text DEFAULT '' NOT NULL, end_date text DEFAULT '' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS settings (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, key text NOT NULL UNIQUE, value text DEFAULT '' NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS audit_logs (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, actor text DEFAULT 'Usuário' NOT NULL, action text NOT NULL, entity text NOT NULL, record_id integer, detail text DEFAULT '' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS niches (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, name text NOT NULL UNIQUE, description text DEFAULT '' NOT NULL, color text DEFAULT '#6d5dfc' NOT NULL, status text DEFAULT 'Ativo' NOT NULL, default_responsible text DEFAULT '' NOT NULL, recommended_product text DEFAULT '' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS lead_import_batches (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, file_name text DEFAULT 'Colagem manual' NOT NULL, source text DEFAULT 'Colagem' NOT NULL, imported_by text DEFAULT 'Equipe comercial' NOT NULL, total_rows integer DEFAULT 0 NOT NULL, imported_rows integer DEFAULT 0 NOT NULL, duplicate_rows integer DEFAULT 0 NOT NULL, skipped_rows integer DEFAULT 0 NOT NULL, error_rows integer DEFAULT 0 NOT NULL, niches_found integer DEFAULT 0 NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS imported_leads (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, batch_id integer, name text DEFAULT '' NOT NULL, company text DEFAULT '' NOT NULL, niche_id integer, niche_name text DEFAULT 'Sem nicho' NOT NULL, phone text DEFAULT '' NOT NULL, whatsapp text DEFAULT '' NOT NULL, email text DEFAULT '' NOT NULL, instagram text DEFAULT '' NOT NULL, site text DEFAULT '' NOT NULL, city text DEFAULT '' NOT NULL, state text DEFAULT '' NOT NULL, source text DEFAULT 'Importação' NOT NULL, responsible text DEFAULT '' NOT NULL, contact_status text DEFAULT 'Não contatado' NOT NULL, product_interest text DEFAULT '' NOT NULL, potential_value real DEFAULT 0 NOT NULL, last_contact text DEFAULT '' NOT NULL, next_followup text DEFAULT '' NOT NULL, notes text DEFAULT '' NOT NULL, custom_fields text DEFAULT '{}' NOT NULL, pipeline_lead_id integer, imported_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS lead_contact_history (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, imported_lead_id integer NOT NULL, actor text DEFAULT 'Equipe comercial' NOT NULL, old_status text DEFAULT '' NOT NULL, new_status text NOT NULL, note text DEFAULT '' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS lead_pipeline_links (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, imported_lead_id integer NOT NULL UNIQUE, pipeline_lead_id integer NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS import_errors (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, batch_id integer NOT NULL, row_number integer NOT NULL, error text NOT NULL, raw_data text DEFAULT '{}' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS team_members (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, name text NOT NULL, email text DEFAULT '' NOT NULL, color text DEFAULT '#6d5dfc' NOT NULL, role text DEFAULT 'Vendedor' NOT NULL, permissions text DEFAULT 'calendar:write,documents:read,ai:read' NOT NULL, status text DEFAULT 'Ativo' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS calendar_events (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, title text NOT NULL, description text DEFAULT '' NOT NULL, start_at text NOT NULL, end_at text NOT NULL, all_day integer DEFAULT false NOT NULL, owner_id integer NOT NULL, visibility text DEFAULT 'Equipe' NOT NULL, category text DEFAULT 'Reunião' NOT NULL, color text DEFAULT '#6d5dfc' NOT NULL, location text DEFAULT '' NOT NULL, meeting_link text DEFAULT '' NOT NULL, lead_id integer, task_id integer, followup_lead_id integer, recurrence text DEFAULT 'Nenhuma' NOT NULL, reminder_minutes integer DEFAULT 15 NOT NULL, status text DEFAULT 'Agendado' NOT NULL, version integer DEFAULT 1 NOT NULL, created_by text DEFAULT 'Equipe comercial' NOT NULL, updated_by text DEFAULT 'Equipe comercial' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS event_participants (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, event_id integer NOT NULL, member_id integer NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS event_audit_logs (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, event_id integer NOT NULL, actor text NOT NULL, action text NOT NULL, detail text DEFAULT '' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS documents (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, object_key text NOT NULL UNIQUE, file_name text NOT NULL, mime_type text NOT NULL, size integer DEFAULT 0 NOT NULL, category text DEFAULT 'Geral' NOT NULL, description text DEFAULT '' NOT NULL, visibility text DEFAULT 'Equipe' NOT NULL, uploaded_by text NOT NULL, version integer DEFAULT 1 NOT NULL, status text DEFAULT 'Disponível' NOT NULL, linked_entity text DEFAULT '' NOT NULL, linked_record_id integer, preview_data text DEFAULT '' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS document_versions (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, document_id integer NOT NULL, object_key text NOT NULL, version integer NOT NULL, size integer DEFAULT 0 NOT NULL, uploaded_by text NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS ai_conversations (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, title text DEFAULT 'Nova conversa' NOT NULL, owner_email text NOT NULL, status text DEFAULT 'Ativa' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS ai_messages (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, conversation_id integer NOT NULL, role text NOT NULL, content text NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS ai_usage_logs (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, conversation_id integer, actor_email text NOT NULL, model text NOT NULL, input_tokens integer DEFAULT 0 NOT NULL, output_tokens integer DEFAULT 0 NOT NULL, status text DEFAULT 'Concluído' NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS ai_tool_calls (id integer PRIMARY KEY AUTOINCREMENT NOT NULL, conversation_id integer NOT NULL, actor_email text NOT NULL, tool_name text NOT NULL, arguments text DEFAULT '{}' NOT NULL, result_summary text DEFAULT '' NOT NULL, mutation integer DEFAULT false NOT NULL, confirmed integer DEFAULT false NOT NULL, created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS settings_key_unique ON settings (key)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS niches_name_unique ON niches (name)`,
      `CREATE INDEX IF NOT EXISTS imported_leads_email_idx ON imported_leads (email)`,
      `CREATE INDEX IF NOT EXISTS imported_leads_whatsapp_idx ON imported_leads (whatsapp)`,
      `CREATE INDEX IF NOT EXISTS imported_leads_niche_idx ON imported_leads (niche_id)`,
      `CREATE INDEX IF NOT EXISTS imported_leads_status_idx ON imported_leads (contact_status)`,
      `CREATE INDEX IF NOT EXISTS imported_leads_batch_idx ON imported_leads (batch_id)`,
      `CREATE INDEX IF NOT EXISTS lead_contact_history_lead_idx ON lead_contact_history (imported_lead_id)`,
      `CREATE INDEX IF NOT EXISTS calendar_events_start_idx ON calendar_events (start_at)`,
      `CREATE INDEX IF NOT EXISTS calendar_events_owner_idx ON calendar_events (owner_id)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS event_participants_unique ON event_participants (event_id, member_id)`,
      `CREATE INDEX IF NOT EXISTS event_participants_event_idx ON event_participants (event_id)`,
      `CREATE INDEX IF NOT EXISTS event_audit_logs_event_idx ON event_audit_logs (event_id)`,
      `CREATE INDEX IF NOT EXISTS documents_updated_idx ON documents (updated_at)`,
      `CREATE INDEX IF NOT EXISTS documents_link_idx ON documents (linked_entity, linked_record_id)`,
      `CREATE INDEX IF NOT EXISTS document_versions_document_idx ON document_versions (document_id)`,
      `CREATE INDEX IF NOT EXISTS ai_conversations_owner_idx ON ai_conversations (owner_email)`,
      `CREATE INDEX IF NOT EXISTS ai_messages_conversation_idx ON ai_messages (conversation_id)`,
      `UPDATE imported_leads SET pipeline_lead_id = NULL, updated_at = CURRENT_TIMESTAMP WHERE pipeline_lead_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM leads WHERE leads.id = imported_leads.pipeline_lead_id)`,
      `DELETE FROM lead_pipeline_links WHERE NOT EXISTS (SELECT 1 FROM leads WHERE leads.id = lead_pipeline_links.pipeline_lead_id) OR NOT EXISTS (SELECT 1 FROM imported_leads WHERE imported_leads.id = lead_pipeline_links.imported_lead_id)`,
      `INSERT INTO team_members (id, name, email, color, role, permissions) SELECT 1, 'Integrante 1', '', '#6d5dfc', 'Administrador', 'calendar:write,documents:write,ai:read,team:write' WHERE NOT EXISTS (SELECT 1 FROM team_members)`,
      `INSERT OR IGNORE INTO team_members (id, name, email, color, role, permissions) VALUES (2, 'Integrante 2', '', '#3478eb', 'Vendedor', 'calendar:write,documents:read,ai:read')`,
      `DELETE FROM team_members WHERE lower(trim(name)) = 'bianca'`,
    ];
    ready = db.batch(statements.map((statement) => db.prepare(statement)));
  }
  return ready;
}
